name: example
description: "A new Flutter project."

publish_to: 'none' 


environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  custom_icon:
    git:
      url: git@github.com:christiancolmanpy/custom_icons.git
      ref: 0f8252b
 



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true
