name: example
description: "A new Flutter project."
version: 2.0.0

publish_to: none 


environment:
  sdk: ">=2.17.0 <3.0.0"



dependencies:
  flutter:
    sdk: flutter
  custom_icon:
    git:
      url: git@github.com:christiancolmanpy/custom_icons.git
      ref: develop

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true
