name: custom_icon
description: Un paquete personalizado que incluye una fuente y un archivo Dart.
version: 0.0.1
homepage: https://github.com/christiancolmanpy/custom_icons.git
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Custom
      fonts:
        - asset: lib/assets/fonts/custom.ttf
  uses-material-design: true